{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.8.5.aar",
          "url": "lifecycle-viewmodel-savedstate-2.8.5.aar",
          "size": 37818,
          "sha512": "fc1d3b21eb1e87cc827df1e6f8c066683c2d3d4f32abe569bf633cde23c6e843453bc8d16c67f0b3c2f834b63696ae45ede6fc0284202ed2092f172e158b5758",
          "sha256": "6f72f2e4fd1e78b255ca908444f39c71e978dc3b05f4bd7198b24c659deab0ec",
          "sha1": "171cb6f4b67053a59011340fdd207cb467b4b2fb",
          "md5": "8a3dacf2424a44d6767ede3d352eabe5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.8.5.aar",
          "url": "lifecycle-viewmodel-savedstate-2.8.5.aar",
          "size": 37818,
          "sha512": "fc1d3b21eb1e87cc827df1e6f8c066683c2d3d4f32abe569bf633cde23c6e843453bc8d16c67f0b3c2f834b63696ae45ede6fc0284202ed2092f172e158b5758",
          "sha256": "6f72f2e4fd1e78b255ca908444f39c71e978dc3b05f4bd7198b24c659deab0ec",
          "sha1": "171cb6f4b67053a59011340fdd207cb467b4b2fb",
          "md5": "8a3dacf2424a44d6767ede3d352eabe5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.8.5-versionMetadata.json",
          "url": "lifecycle-viewmodel-savedstate-2.8.5-versionMetadata.json",
          "size": 2985,
          "sha512": "341d86ea01aa83fe47b6e81db0ec6e8c4cab5472ce77468249903da37a5c58e56dd40960e3f06aa1445bb121c6206e629c3a9415ddae0225ef360c4ad6f5aa68",
          "sha256": "ad4d7cc3757e3a4a155a7986628631aadf18aaeef3a8db68f7f102a45138480c",
          "sha1": "3cfdd21ea6e9fc90baf43d65fff5611a9e8b7ceb",
          "md5": "e534216028fe3fd466ecaaf458d10732"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.5"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.8.5-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.8.5-sources.jar",
          "size": 16154,
          "sha512": "1ffcef56f26e860503ca08c9fdbd808939af5aa7bc01215312c62193e9a407f28d1223b80d7d683d354dc218c3d97e447ce4d254857b18299e8e0c82189a5dd3",
          "sha256": "e2a94fd97d7ecc72b7716dc98995fab44be80caf426d9fdb407b2109d4f853b1",
          "sha1": "2010eace55477ddd72ad8c5dbbcf361d037bdac8",
          "md5": "2ae1d7f51a8a418468facb7f8943e5ba"
        }
      ]
    }
  ]
}