{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.8.3-sources.jar",
          "url": "fragment-ktx-1.8.3-sources.jar",
          "size": 6463,
          "sha512": "723352b2d588e5ca2c9e48e2e03e24ecd1f9d9ded02295eddc67c551b0235e5c18c46bba686c11842e3c1d9601616138df8dad6d954bb2cd306fca4c6219e6a6",
          "sha256": "6c9da4629e5057aa9f7caf9c2f6f77da387b0dec681d3dd65662d33c0871f7ca",
          "sha1": "2a6b134c40d38415440fc6a109024c0c04cc2001",
          "md5": "5ec70084c7c8d7cb5900646cb0923026"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.8.3.aar",
          "url": "fragment-ktx-1.8.3.aar",
          "size": 27608,
          "sha512": "763039582ae3cab610df736884b8e7d121f7b866ce78c1e090966fa385cfdc543f0fe9c6aeaf90705caf3231adb0f94dfecbb97cd9a63b7b4278a6700502c156",
          "sha256": "6349f112b40dd2849bb66bbed27d83c83893c9b061f5fc50c76e8b798ff71bd6",
          "sha1": "048841e8a9e8cc26c22c4730d688f8e58aabe57d",
          "md5": "66c6249bbda358cc197bdbb471dfb0cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.8.3.aar",
          "url": "fragment-ktx-1.8.3.aar",
          "size": 27608,
          "sha512": "763039582ae3cab610df736884b8e7d121f7b866ce78c1e090966fa385cfdc543f0fe9c6aeaf90705caf3231adb0f94dfecbb97cd9a63b7b4278a6700502c156",
          "sha256": "6349f112b40dd2849bb66bbed27d83c83893c9b061f5fc50c76e8b798ff71bd6",
          "sha1": "048841e8a9e8cc26c22c4730d688f8e58aabe57d",
          "md5": "66c6249bbda358cc197bdbb471dfb0cc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "fragment-ktx is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.8.3-versionMetadata.json",
          "url": "fragment-ktx-1.8.3-versionMetadata.json",
          "size": 4141,
          "sha512": "adc0c7700389eddfdd51d42cf2f3f85887d41a09c141d54aa177d847e164d879945e4ac3f55d4781987f34d2954f7bcdb4a44c4b9d1fb37f1da864ecab0aa401",
          "sha256": "fe8221b4d329b0d0e1a2d578c3459a1b9280eececff612ef58dff9602c30fcae",
          "sha1": "dd65ccffb4051e027c95f8f9e3fd1875da7ca2ad",
          "md5": "f83a4e03a0be030d73ccc4d3d6ed8830"
        }
      ]
    }
  ]
}