{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.androidx.core",
    "module": "core-bundle",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "core-bundle-metadata-1.0.0.jar",
          "url": "core-bundle-1.0.0.jar",
          "size": 15100,
          "sha512": "652903ca64d9741ca4c5d9b45b7df5d6df1b6dabf01a72e8c171daa96f8a04c832176a1e93b01ad4c2afcf51d1be6936213a5c99c19faccc28ffa8fe5dfd7449",
          "sha256": "d2b0db564a120544ecda87cb331d0d5bbf05121187deedf30522c45b77a8a0f9",
          "sha1": "51405593bb750558bed81a1f4342486d97908c53",
          "md5": "534f95cb68f6526c4793bf9fde593229"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-bundle-kotlin-1.0.0-sources.jar",
          "url": "core-bundle-1.0.0-sources.jar",
          "size": 6831,
          "sha512": "7cf12b9da74dfce06f624d972971df47ffc22ac9f833f40321daa293964b2a519ddcbcda27a92283149c2237a357291ba23f3eb0efb88a825d31013cbda8a3cd",
          "sha256": "53d6f6d58f8f17c49799f5f25d588bd2079b599db31bccb4e0c7834b9bbb13df",
          "sha1": "0eaa505adddf62f71efe2a27868a4cfa6d0b7167",
          "md5": "cb107f10c684032c8fe2e11ca82bfb3c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android-debug/1.0.0/core-bundle-android-debug-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android-debug",
        "version": "1.0.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android-debug/1.0.0/core-bundle-android-debug-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android-debug",
        "version": "1.0.0"
      }
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android-debug/1.0.0/core-bundle-android-debug-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android-debug",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android/1.0.0/core-bundle-android-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android/1.0.0/core-bundle-android-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-bundle-android/1.0.0/core-bundle-android-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-bundle-desktop/1.0.0/core-bundle-desktop-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-bundle-desktop/1.0.0/core-bundle-desktop-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-bundle-desktop/1.0.0/core-bundle-desktop-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-desktop",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosarm64/1.0.0/core-bundle-iosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosarm64/1.0.0/core-bundle-iosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosarm64/1.0.0/core-bundle-iosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iossimulatorarm64/1.0.0/core-bundle-iossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iossimulatorarm64/1.0.0/core-bundle-iossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iossimulatorarm64/1.0.0/core-bundle-iossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosx64/1.0.0/core-bundle-iosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosx64/1.0.0/core-bundle-iosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-iosx64/1.0.0/core-bundle-iosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-iosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-bundle-js/1.0.0/core-bundle-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-bundle-js/1.0.0/core-bundle-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-bundle-js/1.0.0/core-bundle-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-linuxarm64/1.0.0/core-bundle-linuxarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-linuxarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-linuxarm64/1.0.0/core-bundle-linuxarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-linuxarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-linuxx64/1.0.0/core-bundle-linuxx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-linuxx64/1.0.0/core-bundle-linuxx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosarm64/1.0.0/core-bundle-macosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosarm64/1.0.0/core-bundle-macosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosarm64/1.0.0/core-bundle-macosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosx64/1.0.0/core-bundle-macosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosx64/1.0.0/core-bundle-macosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-macosx64/1.0.0/core-bundle-macosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-macosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-mingwx64/1.0.0/core-bundle-mingwx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-mingwx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-mingwx64/1.0.0/core-bundle-mingwx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-mingwx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosarm64/1.0.0/core-bundle-tvosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosarm64/1.0.0/core-bundle-tvosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosarm64/1.0.0/core-bundle-tvosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvossimulatorarm64/1.0.0/core-bundle-tvossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvossimulatorarm64/1.0.0/core-bundle-tvossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvossimulatorarm64/1.0.0/core-bundle-tvossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosx64/1.0.0/core-bundle-tvosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosx64/1.0.0/core-bundle-tvosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-tvosx64/1.0.0/core-bundle-tvosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-tvosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-bundle-wasm-js/1.0.0/core-bundle-wasm-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-bundle-wasm-js/1.0.0/core-bundle-wasm-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-bundle-wasm-js/1.0.0/core-bundle-wasm-js-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-wasm-js",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm32/1.0.0/core-bundle-watchosarm32-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm32/1.0.0/core-bundle-watchosarm32-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm32/1.0.0/core-bundle-watchosarm32-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm32",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm64/1.0.0/core-bundle-watchosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm64/1.0.0/core-bundle-watchosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosarm64/1.0.0/core-bundle-watchosarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchossimulatorarm64/1.0.0/core-bundle-watchossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchossimulatorarm64/1.0.0/core-bundle-watchossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchossimulatorarm64/1.0.0/core-bundle-watchossimulatorarm64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchossimulatorarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosx64/1.0.0/core-bundle-watchosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosx64/1.0.0/core-bundle-watchosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-bundle-watchosx64/1.0.0/core-bundle-watchosx64-1.0.0.module",
        "group": "org.jetbrains.androidx.core",
        "module": "core-bundle-watchosx64",
        "version": "1.0.0"
      }
    }
  ]
}