name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create dummy google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "firebase_url": "https://dummy.firebaseio.com",
              "project_id": "dummy",
              "storage_bucket": "dummy.appspot.com"
            },
            "client": [{
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:abcdef",
                "android_client_info": {
                  "package_name": "com.guicarneirodev.goniometro"
                }
              },
              "api_key": [{
                "current_key": "dummy_api_key"
              }]
            }]
          }' > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: |
            adb logcat "*:E" &
            ./gradlew connectedAndroidTest --stacktrace

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            app/build/reports/
            app/build/outputs/androidTest-results/
