name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Create google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "dummy",
              "storage_bucket": "dummy.appspot.com"
            },
            "client": [{
              "client_info": {
                "mobilesdk_app_id": "1:123456789:android:abcdef",
                "android_client_info": {
                  "package_name": "com.guicarneirodev.goniometro"
                }
              },
              "api_key": [{"current_key": "dummy_api_key"}]
            }]
          }' > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          target: google_apis
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: |
            ./gradlew connectedAndroidTest --stacktrace

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/outputs/androidTest-results
