name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11  # Mudança aqui para Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Mudança aqui para '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle Info
        run: ./gradlew --version

      - name: Clean project
        run: ./gradlew clean

      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      - name: Generate Test Report
        if: always()
        run: ./gradlew testDebugUnitTest

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            **/build/reports/
            **/build/test-results/
