{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core-viewmodel/4.0.0/koin-core-viewmodel-4.0.0.module",
    "group": "io.insert-koin",
    "module": "koin-core-viewmodel",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.core",
          "module": "core-bundle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-viewmodel-jvm-4.0.0.jar",
          "url": "koin-core-viewmodel-jvm-4.0.0.jar",
          "size": 123466,
          "sha512": "8431426db7319b21ba9f22e32dab2bdc12eecd5756d8ceedbddfc078ce26b89ea925523e6684ef005702c763e1502afc75c81ce056f6f5b2a65130780989391c",
          "sha256": "714fec71c4eb4d935a6576c80e6c98fd11582aa165de9937028ceabe9010085a",
          "sha1": "84f174c13daeb76a9740e050eb131c33c8308c0f",
          "md5": "0c8a54c84f9783a11fa59f28f280d0bf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.core",
          "module": "core-bundle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-viewmodel-jvm-4.0.0.jar",
          "url": "koin-core-viewmodel-jvm-4.0.0.jar",
          "size": 123466,
          "sha512": "8431426db7319b21ba9f22e32dab2bdc12eecd5756d8ceedbddfc078ce26b89ea925523e6684ef005702c763e1502afc75c81ce056f6f5b2a65130780989391c",
          "sha256": "714fec71c4eb4d935a6576c80e6c98fd11582aa165de9937028ceabe9010085a",
          "sha1": "84f174c13daeb76a9740e050eb131c33c8308c0f",
          "md5": "0c8a54c84f9783a11fa59f28f280d0bf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "koin-core-viewmodel-jvm-4.0.0-sources.jar",
          "url": "koin-core-viewmodel-jvm-4.0.0-sources.jar",
          "size": 10336,
          "sha512": "cf192d60c52230f7f45ed3ff4266f2a4a1c002e659a229dee1ee4b0ce746863b3831f70fcebd73d4eff1a1f928fe126bd240377a9ac9ae7451a17b8a054e5726",
          "sha256": "f540a079bc3a993e55ff65001329c704dab35594b8676bb12b7c781457f2745d",
          "sha1": "48374e0a5ac39962b270836408c27824c2019871",
          "md5": "735227d34d9bb2d7bbeaff6afaa93997"
        }
      ]
    }
  ]
}
